# Generated by Django 3.2.5 on 2022-06-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(default='', upload_to='input/')),
                ('img_original', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': '게시판그림',
                'verbose_name_plural': '게시판그림(들)',
                'db_table': 'Akbo_image',
            },
        ),
    ]
