# Generated by Django 3.2.5 on 2022-06-28 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='image',
            new_name='Input',
        ),
        migrations.AlterModelTable(
            name='input',
            table='Akbo_input',
        ),
    ]
