# Generated by Django 3.2.5 on 2022-06-27 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20, verbose_name='아이디')),
                ('password', models.CharField(max_length=500, verbose_name='비밀번호')),
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저(들)',
                'db_table': 'Akbo_user',
            },
        ),
        migrations.CreateModel(
            name='Akbo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='제목')),
                ('artist', models.CharField(max_length=20, null=True, verbose_name='아티스트')),
                ('image', models.FileField(upload_to='akbo_image/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': '악보',
                'verbose_name_plural': '악보(들)',
                'db_table': 'Akbo_akbo',
            },
        ),
    ]
