# Generated by Django 3.2.5 on 2022-07-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='akbo',
            name='lyrics',
            field=models.TextField(null=True, verbose_name='가사'),
        ),
    ]
